### ISSUE TITLE
Make target parameter optional (RDT-854)

### ISSUE THREAD

**Issue by Dzarda7** [espressif/idf-build-apps#146]
Hello @hfudev,
I have proposal for possible enhancement for this project. Do you think it might be possible to make the target parameter optional especially for the build option? I have a use case where it will build the apps with default target (esp32) if not specified otherwise in the sdkconfig.defaults. What do you think about this? This way you can specify the targets in the sdkconfig.defaults and build it with one command. Thanks.

**Comment by hfudev** [comment]
@Dzarda7 Thanks for the idea. yes, it makes sense to simplify the users inputs.

I'll set the default value `targets=all`. By specify the `CONFIG_IDF_TARGET=esp32` inside your `sdkconfig.defaults` files, only `esp32` will be built.

**Comment by Dzarda7** [comment]
Thanks, I might use that in esp-serial-flasher.

**Comment by Dzarda7** [comment]
Awesome, thanks for the quick improvement.

**Comment by Dzarda7** [comment]
I tested it and it works.
