### ISSUE TITLE
Add option to omit default configs (RDT-412)

### ISSUE THREAD

**Issue by tore-espressif** [espressif/idf-build-apps#16]
Add option to build only defined app configurations, excluding the default configuration.

So if I do
```
idf_build_apps find --config sdkconfig.bsp.* -some_flag -t all
```
only the `sdkconfig.bsp.*` configurations are found and no default configurations are added to the list

Related to https://github.com/espressif/esp-bsp/pull/118

**Comment by hfudev** [comment]
created #17, seems like that one would be a cleaner solution that works both on `idf.py build` and `python -m idf_build_apps` sides.
