### ISSUE TITLE
Support env var `SDKCONFIG_DEFAULTS` (RDT-413)

### ISSUE THREAD

**Issue by hfudev** [espressif/idf-build-apps#17]
Now we're using hard-coded `sdkconfig.defaults` and `sdkconfig.defaults.<target>` for all build.

`SDKCONFIG_DEFAULTS` is a ESP-IDF build property. Support this env var as well.

| use case | default sdkconfig file |
|--- | --- |
| `SDKCONFIG_DEFAULTS = ""` or no such env var declared| `sdkconfig.defaults` |
| `SDKCONFIG_DEFAULTS = ";"` | no default file |
| `SDKCONFIG_DEFAULTS = "a;b" | `a`, `b` |

Besides, if declared `<sdkconfig_file>`, consider `<sdkconfig_file>.<target>` as well.

**Comment by igrr** [comment]
Another (maybe better?) option would be to let the build system perform environment variable expansion in sdkconfig files. The only reason why idf-build-apps needs to manage generation of sdkconfig files is that variable expansion feature:
https://github.com/espressif/idf-build-apps/blob/4b208b7ffa2d9196a4eeb1f060762b2bba53a286/idf_build_apps/app.py#L248-L256

**Comment by hfudev** [comment]
@igrr Yes. I'll add support `<config_name>.<target>` in ESP-IDF later.

**Comment by igrr** [comment]
Support for `<config_name>.<target>` is already in IDF: https://github.com/espressif/esp-idf/blob/47852846d3e89580ef4da28210b6ffc1cb5eaa9d/tools/cmake/kconfig.cmake#L112-L119 ([docs](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/build-system.html#target-dependent-sdkconfig-defaults)). My comment was just about variable expansion — that's the only reason for duplicating this functionality in idf-build-apps. If we didn't need it or we did it in IDF, we could have just passed the SDKCONFIG_DEFAULTS list to the IDF build system.

**Comment by hfudev** [comment]
@igrr Thanks. I don't know that is already been implemented. I'll revise the PR.
