### ISSUE TITLE
idf_build_apps does not honor `IDF_EXTRA_ACTIONS_PATH` env variable (RDT-424)

### ISSUE THREAD

**Issue by tore-espressif** [espressif/idf-build-apps#30]
Even though path to `idf.py` is taken from env var `IDF_PATH`, the extra actions from `IDF_EXTRA_ACTIONS_PATH` env variable are not loaded.

Could this be fixed @hfudev ?

**Comment by hfudev** [comment]
Hi @tore-espressif! I don't know this env var before. this one is used for searching idf.py extensions right?

I think PR #20 could solve this issue as well. https://github.com/espressif/idf-build-apps/pull/20/files#diff-10e54fbee51565993785f6adf8d3b1b4dfeaa55e0a13fa77d895f4b4d816fa56R218

while running the `subprocess_run`, the current `os.enviorn` would be copied.

**Comment by tore-espressif** [comment]
Yep, seems like that should fix it, thanks!

(ICYMI: https://github.com/espressif/esp-idf/blob/master/tools/idf_py_actions/README.md)
