### ISSUE TITLE
[Feature request] Build merged binaries (RDT-425)

### ISSUE THREAD

**Issue by XDanielPaul** [espressif/idf-build-apps#32]
I suggest adding a flag to build merged binaries.

**Comment by hfudev** [comment]
my main concern is, adding this feature will add one more dependency `esptool`.

**Comment by lijunru-hub** [comment]
Supporting this feature can assist the warehouse in producing esp launchpad bins more efficiently.

**Comment by lijunru-hub** [comment]
It is best to customize the format of the bin generated by the merge

**Comment by hfudev** [comment]
could be done by users after #100

**Comment by hfudev** [comment]
could be done with `_post_build` function. PTAL https://github.com/espressif/idf-build-apps/pull/111
