### ISSUE TITLE
`--format xunit` for build output (RDT-436)

### ISSUE THREAD

**Issue by hfudev** [espressif/idf-build-apps#35]
Generate one JUnit Report for build jobs as well.

As an example

```html
<testsuites>
    <testsuite errors="0" failures="0" hostname="GARM-C2-WX-1-R5S4N264" name="Build target esp32 in example folder" skipped="0" tests="30" failures="1" time="1051.215" timestamp="2022-12-15T13:25:17.689181">
        <testcase file="examples/get_started/hello_world" name="esp32.default.examples/get-started/hello_world" time="60.2454">
            <failure message="build warnings or error message">
                detailed warnings/errors
            </failure>
        </testcase>
    </testsuite>
</testsuites>
```

Record the following things:
- warnings and errors in <testcase> subtag <failure>
- total duration time and runner info in the <testsuite> attributes
- build duration time in the <testcase> attributes

**Comment by igrr** [comment]
I would also ask for idf_size json output to be saved in attributes. (Maybe via some option/flag, if the reports get too big otherwise.)
