### ISSUE TITLE
[Errno 63] File name too long (RDT-586)

### ISSUE THREAD

**Issue by ramiws** [espressif/idf-build-apps#85]
`
idf-build-apps find -p . --target esp32s3 --config sdkconfig.prd --work-dir ./prdbuild/work --build-dir ./prdbuild/build 

App ., target esp32s3, sdkconfig sdkconfig.prd
`
Then running same command but for build 

idf-build-apps build -p . --target esp32s3 --config sdkconfig.prd --work-dir ./prdbuild/work --build-dir ./prdbuild/build 
Gives this but much much more lines 
`
"[Errno 63] File name too long: './prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/build/esp-idf/ulp'"), ('./prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/prdbuild/work/bui
`

**Comment by ramiws** [comment]
The problem is that when the work directory is inside the project folder, then it copies the whole folder including the work directory, then this happen, if I try to set the work directory outside the project folder then I get:
`
idf-build-apps build -p . --target esp32s3 --config sdkconfig.prd --work-dir ../prdbuild/work --build-dir ../prdbuild/buildprd 
Please use idf.py only in an ESP-IDF shell environment.
2023-11-10 15:31:44    ERROR >>> Last 25 lines from the build log "None":
2023-11-10 15:31:44    ERROR >>> Please use idf.py only in an ESP-IDF shell environment.
2023-11-10 15:31:44    ERROR >>> Build failed with exit code 1
`

the current folder has:
components/
main/
CMakeLists.txt/
sdkconfig.defaults
sdkconfig.prd


version is latest, (pip list did not work on my macos)
Please fix fast or provide work around, I need to build this app with the "sdkconfig.prd"

**Comment by ramiws** [comment]
I think the solution is that in the code which copies the whole code of the app to the working folder, should not copy the working folder, as I provided the name  "--work-dir ./prdbuild/work" so do not copy "prdbuild"

**Comment by ramiws** [comment]
Package        Version
-------------- -------
idf-build-apps 1.1.2

**Comment by ramiws** [comment]
Yes, in my case if you see the first port the Find command runs fine, but the build will show the issue.

**Comment by igrr** [comment]
@hfudev I think I ran into this issue as well, it happens when the work directory is inside the project directory.

Over here: https://github.com/espressif/idf-build-apps/blob/06a91499ea720668705a2fc77f5680071d013264/idf_build_apps/app.py#L446

we can ignore the source directory, like this:

https://github.com/espressif/esp-idf/blob/c8243465e45489835d645bf217a6929fd0c01b7f/tools/test_build_system/conftest.py#L81-L87

**Comment by ramiws** [comment]
thank you @igrr you always come out of nowhere and save mylife :) @hfudev  could you deploy the fix ?

**Comment by hfudev** [comment]
hi @ramiws [1.1.3](https://pypi.org/project/idf-build-apps/1.1.3/) has been released. Please update your version by `pip install -U idf-build-apps`
